feat: services and schedule of services logic added along other minor details

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -1,43 +1,46 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# ESLint is a tool for identifying and reporting on patterns
-# found in ECMAScript/JavaScript code.
-# More details at https://github.com/eslint/eslint
-# and https://eslint.org
-
 name: ESLint
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [main]
   pull_request:
-    # The branches below must be a subset of the branches above
-    branches: [ "main" ]
-  schedule:
-    - cron: '25 2 * * 5'
+    branches: [main]
 
 jobs:
   eslint:
-    name: Run eslint scanning
+    name: Run ESLint scanning
     runs-on: ubuntu-latest
     permissions:
       contents: read
       security-events: write
-      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      actions: read
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Run ESLint
-        env:
-          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
-        run: npm run lint -- --output-file eslint-results.sarif
-        continue-on-error: true
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+          cache: 'npm'
 
-      - name: Upload analysis results to GitHub
-        uses: github/codeql-action/upload-sarif@v3
+      - name: Install dependencies
+        run: npm i
+
+      - name: Run ESLint
+        run: npm run lint -- --output-file eslint-results.sarif
+
+      - name: Upload SARIF results (recommended)
+        uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: eslint-results.sarif
-          wait-for-processing: true
+
+      - name: Check ESLint results and fail workflow if errors are found
+        if: always()
+        run: |
+          npx sarif-utils --level error eslint-results.sarif
+          if [[ $? -eq 1 ]]; then
+            echo "::error::ESLint found errors. Please fix them before merging."
+            exit 1 # Fail the workflow
+          fi
